# Generated by Django 5.2 on 2025-07-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('8-10', '8:00-10:00'), ('10-12', '10:00-12:00'), ('12-2', '12:00-2:00'), ('2-4', '2:00-4:00'), ('4-6', '4:00-6:00')], max_length=5)),
                ('Group_code', models.CharField(max_length=20)),
                ('Group_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['day', 'time_slot'],
                'unique_together': {('day', 'time_slot')},
            },
        ),
    ]
