# Generated by Django 5.2 on 2025-08-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credentials', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='Group_images/default.png', upload_to='Group_images/', verbose_name='Group Image')),
                ('category', models.CharField(choices=[('python', 'Python'), ('web-development', 'Web Development'), ('sql', 'SQL'), ('php', 'PHP')], default='python', max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.instructor')),
            ],
        ),
    ]
